export declare interface BarcodesDb {
    BARCODE: string
    ID_SECTOR: number; 
    SECTOR: string;
    ID_EMPLOYEE: number | null;
    EMPLOYEE: string;
    BLOCKED: number;
}

export declare interface OrderBody {
    id?: number;
    orderId?: number;
    name?: string;
    height?: number;
    width?: number;
    amount?: number;
    square?: number;
    comment?: string;
    unit?: string;
    cost?: number;
    calcAs?: string;
    costSng?: number;
    priceCost?: number;
    priceMod?: string;
    calcComment?: string;
}

export declare interface OrderHeader {
    id?: number;              
    itmOrderNum?: string;  
    client?: string;      
    orderType?: string;  
    viewMode?: string;          
    manager?: string;            
    fasadMaterial?: string;        
    fasadModel?: string;          
    profileWidth?: string;  
    assemblyAngle?: string;       
    texture?: string;            
    filenkaMaterial?: string;   
    filenkaModel?: string;          
    filenkaColor?: string;          
    color?: string;                
    colorType?: string;  
    colorLak?: string;  
    colorLakComment?: string;  
    colorPatina?: string;  
    colorPatinaComment?: string;     
    square?: number; 
    squareFasad?: number;               
    dateFactOrderOut?: string;      
    status?: string;
    statusNum?: number;            
    city?: string;
    cost?: number;
    totalCost?: number;
    pay?: number;
    debt?: number;
    dateFirstStage?: Date;
    dateSave?: string;
    datePlanPack?: Date;
    isPrepaid?: number;
    prisad?: string;
    termoshov?: string;
    textureComment?: string;
    discount?: string;
    discountComment?: string;
    costPack?: number;
    dateLastSave?: string;
    dateCalcCost?: string;
    dateFactPack?: string;
    dateFactOrderOut?: string;
    comment?: string;
    costPriceColumn?: number;
    costUp?: number;
    costUpComment?: string;
}

export declare interface IOrderHeaderDb {
    ID:                      number,
    MANAGER:                 string,
    CLIENT:                  string,
    ORDERNUM:                string,
    ITM_ORDERNUM:            string,
    FASAD_MAT:               string,
    FASAD_MODEL:             string,
    FASAD_PG_WIDTH:          number,
    TEXTURE:                 string,
    FIL_MAT:                 string,
    FIL_MODEL:               string,
    COLOR:                   string,
    FIL_COLOR:               string,
    COLOR_TYPE:              string,
    COLOR_LAK:               string,
    COLOR_PATINA:            string,
    ORDER_GENERALSQ:         number,
    ORDER_FASADSQ:           number,
    GLASS:                   string,
    PRIMECH:                 string,
    ORDER_COST_PRICECOLUMN:  number,
    ORDER_COST:              number,
    ORDER_PAY:               number,
    ORDER_TOTAL_COST:        number,
    ORDER_DISCOUNT:          number,
    ORDER_DISCOUNT_COMMENT:  string,
    ORDER_COSTUP:            number,
    ORDER_COSTUP_COMMENT:    string,
    ORDER_COST_PACK:         number,
    ORDER_COST_GLASS:        number,
    FACT_DATE_RECEIVE:       string,
    FACT_DATE_FIRSTSAVE:     string,
    FACT_DATE_LASTSAVE:      string,
    FACT_DATE_CALCCOST:      string,
    FACT_DATE_EXPORT_ITM:    Date,
    FIRSTSTAGEBAD:           string,
    FACT_DATE_PACK:          string,
    FACT_DATE_ORDER_OUT:     string,
    ORDER_STATUS:            number,
    FACT_DATE_ORDER_CANCEL:  string,
    REASON_ORDER_CANCEL:     string,
    USER_ORDER_CANCELED:     string,
    ORDER_TYPE:              string,
    TEXTURE_COMMENT:         string,
    COLOR_LAK_COMMENT:       string,
    COLOR_PATINA_COMMENT:    string,
    PRISAD:                  string,
    PLAN_DATE_FIRSTSTAGE:    Date,
    PLAN_DATE_PACK:          Date,
    FILEPATH_CALC_CLIENT:    string,
    FILEPATH_CALC_MANAGER:   string,
    FILEPATH_BILL:           string,
    VIEW_MOD:                string,
    TERMOSHOV:               string,
    ASSEMBLY_ANGLE:          string
}
